name: diabetes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  intl_phone_number_input: ^0.7.4
  fluttertoast: ^8.2.1
  cloud_firestore: ^5.5.0 # Use the latest version
  flutter_localizations:
        sdk: flutter
  fl_chart: ^0.69.1
  numberpicker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - fonts/ # Make sure this matches the actual directory where fonts are located
    - images/logo.png
    - images/diabetes_-scaled.jpg
    - images/mobile-phone.png
    - images/profile.jpg
    - images/chat.jpg
    - images/backProfile.jpg
    - images/background.jpg
    - fonts/Roboto-Regular.ttf
    - fonts/Roboto-Bold.ttf
    - fonts/Roboto-Italic.ttf
    - fonts/Times-New-Roman.ttf
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: fonts/Times-New-Roman.ttf
  # fonts:
  #   - family: Roboto  # Font family name
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf  # Regular font
  #       - asset: assets/fonts/Roboto-Bold.ttf     # Bold variant
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf   # Italic variant
  #         style: italic
flutter_native_splash:
  image: images/logo.png
  background_image: images/background.jpg
  android: true
  ios: true
  fullscreen: true
flutter_intl:
  enabled: true
