name: diabetes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  intl_phone_number_input: ^0.7.4
  fluttertoast: ^8.2.1
  cloud_firestore: ^5.5.0 # Use the latest version
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.69.1
  numberpicker: ^2.1.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  local_auth: ^2.1.7
  image_picker: ^0.8.7+4
  # firebase_storage: ^12.0.0
  firebase_app_check: ^0.3.1+7
  shared_preferences: ^2.3.4
  video_player: ^2.5.0
  provider: ^6.1.2
  #cloud_functions: ^4.0.6
  flutter_local_notifications: ^14.0.4
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  pedometer: ^4.0.2
  google_maps_flutter: ^2.10.0
  geolocator: ^11.0.20
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator_android: ^4.6.1
  location: ^5.0.0
  flutter_svg: ^1.1.0
  flutter_map_location_marker: ^8.0.5
  permission_handler: ^10.2.0
  syncfusion_flutter_gauges: ^20.4.38
  flutter_email_sender: ^7.0.0

  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.0.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  generate: true
  
 

  assets:
    - images/
    - fonts/ # Make sure this matches the actual directory where fonts are located
    - assets/images/
    - videos/
    - assets/images/FruitsandVegetables/
    - assets/images/Soups/
    - assets/images/ColdDrinks/
    - assets/images/hotdrinks/
    - assets/images/candies/
    - assets/images/lunch/
    - assets/images/SaladsAndAppetizers/
    - assets/images/breads/
    - assets/images/Diary/
    - assets/images/Breakfast/
    - images/diabetes_-scaled.jpg
    - images/mobile-phone.png
    - images/profile.jpg
    - images/chat.jpg
    - images/backProfile.jpg
    - images/background.jpg
    - images/newdoctor.png
    - images/seated_spinal.jpg
    - images/child_pose.jpg
    - images/seated_forward_bend.jpg
    - images/bow_pose.jpg
    - images/cat_cow.jpg
    - images/legs_up_the_wall.jpg
    - images/triangle_pose.jpg
    - images/plank_pose.jpg
    - images/newsport.png
    - images/remind.png
    - images/welcome.png
    - images/NoProfilePic.png
    - images/track.png
    - videos/Boat-Pose.mp4
    - videos/Bow-Pose.mp4
    - videos/Bridge-Pose.mp4
    - videos/Cat-Cow.mp4
    - videos/Child-Pose.mp4
    - videos/Cobra-Pose.mp4
    - videos/Plank-Pose.mp4
    - videos/Seated_Forward.mp4
    - videos/Seated-Spinal-Twist.mp4
    - videos/Triangle-Pose.mp4
    - videos/Warrior-Pose.mp4
    - fonts/Roboto-Regular.ttf
    - fonts/Roboto-Bold.ttf
    - fonts/Roboto-Italic.ttf
    - fonts/Times-New-Roman.ttf
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: fonts/Times-New-Roman.ttf
  # fonts:
  #   - family: Roboto  # Font family name
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf  # Regular font
  #       - asset: assets/fonts/Roboto-Bold.ttf     # Bold variant
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf   # Italic variant
  #         style: italic
flutter_native_splash:
  image: images/logo.png
  background_image: images/background.jpg
  android: true
  ios: true
  fullscreen: true
flutter_intl:
  enabled: true
