name: diabetes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  fl_chart: ^0.60.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  intl_phone_number_input: ^0.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logo.png
    - images/diabetes_-scaled.jpg
    - images/background.jpg
    # - images/mobile-phone.png
    - assets/fonts/

  fonts:
  - family: CustomFont  # Replace with your font family name
    fonts:
      - asset: assets/fonts/YourFontFile.ttf  # Replace with the actual file name
      - asset: assets/fonts/YourFontFile-Bold.ttf  # Optional: Bold variant
        weight: 700  # Set the weight for bold
      - asset: assets/fonts/YourFontFile-Italic.ttf  # Optional: Italic variant
        style: italic  




flutter_native_splash:
  image: images/logo.png  # Path to your app logo
  background_image: images/background.jpg
  #branding: images/brand.jpg
  android: true  # Enable for Android
  ios: true  # Enable for iOS
  fullscreen: true  # Make the splash screen fullscreen
